### ISSUE TITLE
Unstable graphics

### ISSUE THREAD

**Issue by Kingistel** [technicaljicama/godot-psp#1]
**Operating system or device - Godot version:**
PSP E1008 6.60 PROMOD / Godot 2.1.6 / EBOOT last version

**Issue description** (what happened, and what was expected):
Assembled a standard Godot 2D Pong project, the screen does not clear with each new frame. Remains trace. But at least it started because of its simplicity

**Steps to reproduce:**
Export any game from godot-demo-projects-2.1, done

**Link to minimal example project** (optional but very welcome):
https://github.com/godotengine/godot-demo-projects/tree/2.1/2d/pong

What it looks like
https://user-images.githubusercontent.com/64025073/233856735-e51fe7ee-5c27-47cb-be36-01ba51debf26.MOV

**Comment by technicaljicama** [comment]
You have to disable all the screen related options, so width ,height, stretching, scaling

**Comment by technicaljicama** [comment]
Also a PSP 2000 is recommened for bigger games, since the 1000 crashes on many games because of the RAM (it has 32mb)

**Comment by Kingistel** [comment]
Solution: Uncheck all the checkboxes in Display and there set the native resolution of the PSP
