### ISSUE TITLE
Area2D don't work

### ISSUE THREAD

**Issue by Kystan** [technicaljicama/godot-psp#10]
Area2D nodes do not work (do not start) on psp

There are 2 objects that should include Label when colliding
But it doesn't even start on the console (psp 3000)

Project - 
[New.zip](https://github.com/PSVita-Dev/godot-psp/files/12339242/New.zip)

**Comment by technicaljicama** [comment]
They do work, why shouldn't they? This is not PSP related

**Comment by Kystan** [comment]
that is, this project that I threw off to you is working on your console?

**Comment by technicaljicama** [comment]
Yes it works

**Comment by technicaljicama** [comment]
Not a single gdscript function or node should crash the PSP. Either, you are using a wrong version of Godot PSP (use the latest) or no project will run for whatever reason. Also I highly recommend exporting it directly to a data.pck and not putting the project files on the memcard

**Comment by Kystan** [comment]
maybe some checkboxes should be set when exporting or in the settings?

**Comment by Kystan** [comment]
> 

 memcard - sd?

**Comment by Kystan** [comment]
I use Godot 2.1.6 and templates as well 2.1.6
