### ISSUE TITLE
drop frame

### ISSUE THREAD

**Issue by wesamdev** [technicaljicama/godot-psp#15]
**Operating system or device - Godot version:**
windows ppsspp, 2.1.7 RC

**Issue description** (what happened, and what was expected):

drop frame when game take action, (when action pressed)

**Comment by technicaljicama** [comment]
Shouldn't be a problem... Can I see your code?

**Comment by wesamdev** [comment]
project download https://pixeldrain.com/u/aA9cip4j

**Comment by technicaljicama** [comment]
Because the game tries to load a sound each "flap"

**Comment by wesamdev** [comment]
how to fix that

**Comment by wesamdev** [comment]
....

**Comment by technicaljicama** [comment]
Just don't play a sound each flap
