### ISSUE TITLE
lack of RAM

### ISSUE THREAD

**Issue by Kystan** [technicaljicama/godot-psp#16]
I'm doing a project on psp, about 5 scenes are used. if you switch them in order, then the 4th (for example) will destroy the entire project, but if you run it first, there will be no problem. 
Is there a dynamic memory limit on the psp that is not cleared when the scene switches to a new one?

Moving on to the next one - get_three().change_scene("res://LavelB_0.tscn")
deleting scene from memory - queue_free()

code:
if time1 >= 1 and flag == 7:
get_tree().change_scene("res://LavelB_0.tscn")
queue_free()
flag var = 0

this memory bug will literally ruin my project if it is not resolved:(

Information output:

function _ready():
set_fixed_process(true)
	var os = OS
var static_memory = os.get_static_memory_usage()
var dynamic_memory = os.get_dynamic_memory_usage()
print("Static memory usage:", static_me
[one of the scripts.txt](https://github.com/PSVita-Dev/godot-psp/files/13061764/one.of.the.scripts.txt)
mory, "bytes")
print("Dynamic memory usage:", dynamic_memory, "bytes")

[one of the scripts.txt](https://github.com/PSVita-Dev/godot-psp/files/13061772/one.of.the.scripts.txt)

**Comment by Kystan** [comment]
you can give me personal contacts if you need my entire project.

**Comment by technicaljicama** [comment]
The biggest issue are the texture sizes. So you can try scaling each texture down by 50%

**Comment by Kystan** [comment]
they are cut down very much, but that's not the point, the fact is that my textures show themselves perfectly on the stage, but there is a feeling that the previous scene is not deleted from memory

**Comment by Kystan** [comment]
after conducting several tests, I can say for sure that there is some kind of limit in the storage of scenes that prevents adding new scenes

**Comment by Kystan** [comment]
is there really no way to solve this problem? maybe saving will help somehow?

**Comment by technicaljicama** [comment]
I don't know, it does not sound like a psp specific problem tbh.. (It is but only due to hardware limitations) (Make sure to never try loading textures over 512x512)

**Comment by Kystan** [comment]
all textures up to 480x272

**Comment by Kystan** [comment]
will send you my project?

**Comment by technicaljicama** [comment]
There is not much you can do, other than squeezing the textures down.
