### ISSUE TITLE
PSP shuts off after splash screen

### ISSUE THREAD

**Issue by fatkid5600** [technicaljicama/godot-psp#18]
I am aware it only says PSP 2000, but I don't see why It wouldn't work on a 3000 unless there's something I am unaware about. My game works just as expected in PPSSPP but on my PSP it gets to the splash screen and then a few seconds later my PSP shuts off, I have tried overclocking my PSP to the max, deleting and recopying the files over to my PSP. But it still just shuts off, super strange.

**Comment by technicaljicama** [comment]
How big are your textures?

**Comment by technicaljicama** [comment]
Closing because of no response
