### ISSUE TITLE
Sprites error

### ISSUE THREAD

**Issue by Kystan** [technicaljicama/godot-psp#2]
![IMG_20230426_185423_949](https://user-images.githubusercontent.com/99103936/234632489-21837d3d-34da-40f5-8fcf-c45a0b38c5c1.png)

Sprites on PSP are not displayed correctly

![IMG_20230426_181447](https://user-images.githubusercontent.com/99103936/234632060-41920f15-15e2-4ffb-b1ec-8145c5ff625d.jpg)

![IMG_20230426_181441](https://user-images.githubusercontent.com/99103936/234632070-9dad81c2-a999-45b2-822d-4bfb2fed22e5.jpg)

Here is the minimal project

[Gadot_1.zip](https://github.com/PSVita-Dev/godot-psp/files/11346176/Gadot_1.zip)
Also psp does not perceive multiple scenes (

**Comment by technicaljicama** [comment]
Have a look at #1

**Comment by Kystan** [comment]
according to the characteristics, everything is the same as in the post that you indicated. Perhaps a different format should be used for heavier .png photos?

**Comment by Kystan** [comment]
![IMG_20230427_191257_556](https://user-images.githubusercontent.com/99103936/234924810-f1255b50-3651-45ee-95e7-c30190fe91bd.png)
And another small question, can I somehow change the dead zone for control stick or in other words - sensitivity (here is the "axis of the gamepad") since the psp stick is not very stable :/

**Comment by technicaljicama** [comment]
> according to the characteristics, everything is the same as in the post that you indicated. Perhaps a different format should be used for heavier .png photos?

try using import -> texture, if that doesnt help, just copy the textures into the project folder


> ![IMG_20230427_191257_556](https://user-images.githubusercontent.com/99103936/234924810-f1255b50-3651-45ee-95e7-c30190fe91bd.png) And another small question, can I somehow change the dead zone for control stick or in other words - sensitivity (here is the "axis of the gamepad") since the psp stick is not very stable :/

Not possible unless you modify the code

**Comment by Kystan** [comment]
about textures: zero result
about the stick: could you tell me what lines to write to implement this idea, I will be very grateful :3

**Comment by technicaljicama** [comment]
Can you try the new release?
Also look in platform/PSP/os_psp.cpp in process_keys

**Comment by technicaljicama** [comment]
Also please tell me the width and height of the texture

**Comment by Kystan** [comment]
> Также, пожалуйста, скажите мне ширину и высоту текстуры

![pngegg](https://user-images.githubusercontent.com/99103936/234954151-51f316a6-28fa-4923-961d-fd0a5bfae221.png)
but I tried different formats and the same sizes, different resolutions of the texture, everything is fine only if you stretch the texture to full screen (((

**Comment by technicaljicama** [comment]
That texture is huge! Try scaling it down to 64x64, big textures like that arent profitable on a psp.

**Comment by technicaljicama** [comment]
I encourage you to try the new release

**Comment by Kystan** [comment]
T
![cropped](https://user-images.githubusercontent.com/99103936/234969407-1a515442-6d0f-496e-baf0-64e41f6c6f7d.jpg)
hat texture is huge! Try scaling it down to 64x64, big textures like that arent profitable on a psp. 

the result is the same(

**Comment by Kystan** [comment]
tried the new version, it doesn't help

**Comment by Kystan** [comment]
[Gadot_1.zip](https://github.com/PSVita-Dev/godot-psp/files/11347306/Gadot_1.zip)
here is my project

**Comment by technicaljicama** [comment]
The 2d one?

**Comment by technicaljicama** [comment]
![pngegg](https://user-images.githubusercontent.com/80003809/235060412-789c8edd-4046-422d-bcca-b0bfd7ae0f6c.png)
Can you create a blank project, copy this ^ texture into it and put it in a scene?

**Comment by technicaljicama** [comment]
If all of that doesn't work, I have an idea for a fix

**Comment by Kystan** [comment]
oh, I already solved the problem with the textures thanks)

**Comment by Kystan** [comment]
the only problem left is with the stick, how to set up a dead zone in the code :\
Hope you can help :)

**Comment by technicaljicama** [comment]
You can get the raw axis value in gdscript using InputEventJoystickButton.JOY_BUTTON_0 and 1. (One is the x value and the other the y value iirc)

**Comment by Kystan** [comment]
thank you so much for answering all my questions)

**Comment by technicaljicama** [comment]
I will close this issue now
