### ISSUE TITLE
3D projects and the HOME button

### ISSUE THREAD

**Issue by Kingistel** [technicaljicama/godot-psp#3]
**Operating system or device - Godot version:**
PROMOD 6+, 2.1.6

This code: https://github.com/janmarcano/Dolphin-Island-2/blob/master/scenes/pause.gd
and get_tree().quit()    **drop psp**

3D projects also refuse to work properly so far, yes, on 3d.pbp(eboot). 

Something confused me in your implementation of the HOME button, looked through the source code of other projects, in principle did not find a call for exit functions. I agree that HOME works in principle, but it doesn't call the standard menu and consequently the plugins that are called from it don't work.

**Comment by technicaljicama** [comment]
Because the home button did not go into the menu, I made it so that it will quit

**Comment by technicaljicama** [comment]
3D projects also refuse to work properly so far, yes, on 3d.pbp(eboot). Wdym by that, I made so many tests using 3d, all of them worked

**Comment by technicaljicama** [comment]
What else should get_tree().quit() do?

**Comment by Kingistel** [comment]
> What else should get_tree().quit() do?

Exit the application, useful for the exit button in the game itself.
>Wdym by that, I made so many tests using 3d, all of them worked

Since Godot is not my native engine I did not understand its principles of creating and working with 3D graphics, I'm now talking about the fact that all I tried to stupidly port it does not run. I was expecting that but still sad.

Also for some reason (because Godot can't find the files), I have games crashing in PPSSPP
[logs.txt](https://github.com/PSVita-Dev/godot-psp/files/11359056/logs.txt)

**Comment by technicaljicama** [comment]
When using ppsspp, you have to put the data.pck file where the eboot.pbp is located at

**Comment by Kingistel** [comment]
>When using ppsspp, you have to put the data.pck file where the eboot.pbp is located at

That's where he is.
Godot
----data.pck
----EBOOT.pbp

Works on PSP, but does not work in PPSSPP. I tried "slowing down" the PPSSPP and disabling fast reading, didn't help

**Comment by Kingistel** [comment]
Okay, I'm going to close this topic. For the project to open in PPSSPP you need to throw not data.pck, and unpacked project. **That is, you must have in the same folder EBOOT and engine.cfg**
