### ISSUE TITLE
Custom fonts and working with files

### ISSUE THREAD

**Issue by Kingistel** [technicaljicama/godot-psp#4]
Custom fonts (DynamicFont) and File.READ (f.get_line()) don't work, and I wish they did.

Can you give me some kind of contact for feedback? Creating issues for every little thing that doesn't work isn't very nice.

**Comment by technicaljicama** [comment]
You can join https://discord.gg/2vxbu4PM

**Comment by technicaljicama** [comment]
Also writing files worked, with some sample game

**Comment by Kingistel** [comment]
>Also writing files worked, with some sample game

I don't know, standard reading functions work in windows version but cause crash on PSP or PPSSPP. But it's not as bad as not working Custom font, I want Cyrillic text.
[sample.txt](https://github.com/PSVita-Dev/godot-psp/files/11360090/sample.txt)
Here's the problematic code, it's fine as long as I use a list instead of a file.

**Comment by technicaljicama** [comment]
Closing
