### ISSUE TITLE
Need help to use InputEventJoystickMotion and InputEventJoystickButton

### ISSUE THREAD

**Issue by Kystan** [technicaljicama/godot-psp#6]
Need help to use InputEventJoystickMotion and InputEventJoystickButton

Could you help me understand how to make a dead zone for the PSP stick using these functions. Values must be in the format 0.73657 and 0.57367548 (this is an example)

Here is my code:
	var joy_axis = Input.get_joy_axis(0, 0)
	if joy_axis == 0.5:
		if Input.is_action_pressed("R_Stick"):
			motion1.x += 1
	else:
		if Input.is_action_pressed("R_Stick"):
			motion1.x += 0
			
	if joy_axis == LOLdead_zone:
		if Input.is_action_pressed("L_Stick"):
			motion1.x -= 1
	else:
		if Input.is_action_pressed("L_Stick"):
			motion1.x -= 0

	motion1 = motion1.normalized() * speed
	move_and_slide(motion1)
[Stick.txt](https://github.com/PSVita-Dev/godot-psp/files/11472502/Stick.txt)

**Comment by technicaljicama** [comment]
This is not a psp related issue, I have done analog input by directly mapping joy_axis_0 and joy_axis_1 to x and y

**Comment by Kystan** [comment]
I understand what it is about, but I do not quite understand how to write it in code. Could you send me your code so I can understand enough? I would be extremely grateful to you for this service.

**Comment by technicaljicama** [comment]
I'll send you one soon

**Comment by technicaljicama** [comment]
Input.get_joy_axis(0, JOY_ANALOG_0_X)
Input.get_joy_axis(0, JOY_ANALOG_0_Y)
Input.get_joy_axis(0, JOY_ANALOG_1_X)
Input.get_joy_axis(0, JOY_ANALOG_1_Y)

this is how to get all 4 values from the left stick
