### ISSUE TITLE
Closed after boot Splash

### ISSUE THREAD

**Issue by magarcan** [technicaljicama/godot-psp#7]
Using Godot 2.1.6 Windows x64
Using godot-psp 3rd release

The file boots up, but crashes during boot splash screen.
I've not been able to log the issue, but shoot this capture:
https://i.imgur.com/uY8MAGJ.png

Tested Within SSPPSS 1.15.4
Tested using PSP 2000

Here it goes sample project):
[data.zip](https://github.com/PSVita-Dev/godot-psp/files/11724680/data.zip)

**Comment by technicaljicama** [comment]
Have you done this? settings -> Tools -> developer tools -> Logging channels -> Log level -> select "verb."

**Comment by technicaljicama** [comment]
Also, is ppsspp running in psp2000 mode?

**Comment by magarcan** [comment]
I did.

I also tried in a real PSP 2000.

Emulador get closed and psp reboot.

**Comment by technicaljicama** [comment]
I will test it later

**Comment by technicaljicama** [comment]
Ok, so there are a few things that might cause the issue: 
1. The gdscript script has no file name, it is just called .gd
2. In _ready, you do set_fixed_process(true) but there is no fixed process defined

**Comment by bladesero** [comment]
Tested Within ppsspp 1.15.4, crashed, the same problem, but it can be opened with ppsspp 1.12.3,however,the log ask for .pck and .zip
<img width="1718" alt="image" src="https://github.com/PSVita-Dev/godot-psp/assets/18096279/d7e4776f-37bf-45c4-9244-53e8df2f5941">
<img width="1674" alt="image" src="https://github.com/PSVita-Dev/godot-psp/assets/18096279/e9c37775-eac4-4c5f-8f4f-80633c6a9da2">

**Comment by technicaljicama** [comment]
Yea, i have found out that New ppsspp versions have a problem with it for some reasons. Just copy the data.pck to the virtual PSP memstick in ppsspp (PSP/GAME/Godot/)

**Comment by technicaljicama** [comment]
Should be fixed by now
