### ISSUE TITLE
VideoPlayer .ogv

### ISSUE THREAD

**Issue by Kystan** [technicaljicama/godot-psp#9]
Godot 2.1 - PSP 3006

**Issue description** (what happened, and what was expected):
I used Video Player to play videos in .ogv format
and tried to remove the sound, and compress, and crop, but crashes, as I understand PSP is not designed to play video format .ogv

How to get out of the situation?

[PSP_Prod.zip](https://github.com/PSVita-Dev/godot-psp/files/12270256/PSP_Prod.zip)

**Comment by technicaljicama** [comment]
You can't play video files inside Godot psp. Even the psvita port is not able to play them with an okay performance (last time I checked was 6fps at best). The only thing I *could* do is add a pmfplayer node (the native PSP video format) but then it would be a full screen video and could not really be combined with other graphics

**Comment by Kystan** [comment]
if pmf player can be implemented, then it would be very helpful!
I am also haunted by a problem with the sound in this engine, maybe you know how to add it correctly so that the sound does not break

**Comment by technicaljicama** [comment]
I have just looked at the sdk- a pmf player might not be possible, although some kind of special PSP player is possible. Sound is an interesting one. First of all the developers of Godot have left the original PSP audio driver code in the first version of the engine (https://github.com/godotengine/godot/blob/0b806ee0fc9097fa7bda7ac0109191c9c5e0a1ac/platform/android/.old/audio_driver_android.cpp). The audio is choppy for an yet unknown reason but it MIGHT be better when recompiling the engine with this line removed (https://github.com/PSVita-Dev/godot-psp/blob/psp/platform/psp/audio_driver_psp.cpp#L36) although I haven't tested it because no ppsspp version will work then. I might update it.

**Comment by technicaljicama** [comment]
Also, I remember you asking how to write and laid files, here it is:
func save(content):
    var file = File.new()
    file.open("user://save_game.dat", file.WRITE)
    file.store_string(content)
    file.close()

func load():
    var file = File.new()
    file.open("user://save_game.dat", file.READ)
    var content = file.get_as_text()
    file.close()
    return content

**Comment by technicaljicama** [comment]
https://docs.godotengine.org/en/2.1/classes/class_file.html

**Comment by technicaljicama** [comment]
Audio driver has been fixed in the fifth release!

**Comment by technicaljicama** [comment]
Also, I managed to play a .ogv video using the latest release. The performance is too bad (1 fps at best) so I would need to add a custom one.

**Comment by Kystan** [comment]
You are God, Thank you for your work! The sound works much better, but there is a crackling sound, how can I fix it? Maybe there is some correct way to compress audio?

**Comment by Kystan** [comment]
Another nuance, any image does not work with sound

**Comment by technicaljicama** [comment]
I have just added a stream player node and set an uncompressed ogg file

**Comment by Kystan** [comment]
> I just added a streaming player node and installed an uncompressed ogg file

and everything works?

**Comment by Kystan** [comment]
I use and .jpg .tex .png (more than 100 kb)
The problem is exactly the size, do you know how to quickly and painlessly (practically) reduce the size to 1kb

**Comment by Kystan** [comment]
> Я только что добавил узел потокового проигрывателя и установил несжатый файл ogg

Мне хотелось бы узнать в первую очередь как убрать потрескивание в звуке (звук сам по себе стабилен)
[empty-hallways.zip](https://github.com/PSVita-Dev/godot-psp/files/12323073/empty-hallways.zip)

**Comment by Kystan** [comment]
I found out that the problem may be in the PSP RAM (there is not enough of it), here only if something is solved inside the engine

**Comment by technicaljicama** [comment]
You can always check if the psp runs out of ram if you view the log and if you see something like "condition mem is true" then there is no more ram left. Other than that all assets in the current scene are loaded

**Comment by technicaljicama** [comment]
I always ran out of ram in my fnaf port, it was really hard. It still doesn't run on a PSP 1000.

**Comment by technicaljicama** [comment]
(The fnaf port was written entirely in c++ and all images take up 3MB)

**Comment by Kystan** [comment]
Problem: the code works on PC, but not on psp (it doesn't even load)
	var player_position = get_pos()
	
	var min_position = Vector2(275, 66.203201)
	var max_position = Vector2(387, 66.203201)
	
	if (player_position.x >= min_position.x and player_position.y >= min_position.y and player_position.x <= max_position.x and player_position.y <= max_position.y):
		var label = get_node("Label2")
		label.text = "loldfsbhrt--------------"
is the psp that weak??

**Comment by technicaljicama** [comment]
Why should that code not work? Whate the issue?

**Comment by Kystan** [comment]
It doesn't matter anymore, get_pos() crashed

**Comment by Kystan** [comment]
player_position = get_pos()
